spring:
  transaction:
    rollback-on-commit-failure: true
  h2:
    console:
      enabled: true
      path: /h2-consol
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
